### PR TITLE
replaced old SUB-D-footprints with a more complete new, scripted series

### PR DESCRIPTION
**Pull request by jkriege2**
- shiny new symbol, scripted: https://github.com/pointhi/kicad-footprint-generator/pull/69
- D-SUBs seems pretty standardized, so I relied on these two datasheets: https://disti-assets.s3.amazonaws.com/tonar/files/datasheets/16730.pdf, http://docs-europe.electrocomponents.com/webdocs/1585/0900766b81585df2.pdf
- old 3D models didn't fit anyways and were not very nic (see images at the end), so I didn't try to make them fit and we should try and get new ones ...

## new footprints:
female 9-pin connectors only ... but they are all there ;-)
2017-10-19 23_38_58-3d viewer
2017-10-19 23_38_41-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

## old footprints for comparison:

2017-10-19 23_33_49-3d viewer
2017-10-19 23_33_28-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Jan this looks fantastic. I'm away for the weekend but if no one else has approved this I'll take a look on Sunday or Monday. :)

**Comment by SchrodingersGat** [comment]
* You have misspelled `EdgeMount` as `EgdeMount`
* Instead of `Px1.98mm` it should be `P1.98mm` (this applies for other pitch sizes also)
* There are many footprints where the pins have a horizontal offset which doesn't match the connector:

screenshot from 2017-10-23 00-09-18

**Comment by jkriege2** [comment]
Should be fixed now:
1. typo fixed (thanks!)
2. I added both pitches as `_P{pitchx}x{pitchy}mm` as they are different and there are variants (e.g. observe the _NoBox, which come in two different y-pitches and I assume there are variations in x-pitch on the PCB-layout somewhere ... What do you think? Maybe remove the x-pitch? But then I nee `_Py...mm` to make clear, which pitch is actually meant!
3. THat was a bug in the script for the HD-NoBox-ones ... should be fixed, see below ...

**EDIT: exchanged wrong screenshot!**
2017-10-22 16_25_21-pcbnew d__kicad_test_addlin_test_addlin kicad_pcb

**Comment by jkriege2** [comment]
all KLC-issues (with courtyard) fixed

**Comment by poeschlr** [comment]
Please do not use Angled and Straight use Horizontal and Vertical instead. (The orientation should also be after the pitch field like in all other footprints.)

From the new KLC: (Generic standardized connectors)

`[generic series name]-[pin configuration]_P[pin pitch]{_Pad[pad length]{x[pad width]}}_[orientation]{_footprint options}`

pin configuration: In this case = number of pins (multiple rows but all rows have a different number of pins.
As you correctly identified the pin pitch in this case should be split into `P[pitch X]x[pitch Y]`

And if we want to use the new naming scheme you should remove `mm`

**Comment by jkriege2** [comment]
Hmmm ... with that I have two problems:
1. What is "horizontal" and what is "vertical" in that connector, the direction in which I put in the plug? ... angled and straight is IMHO much clearer, as it literally describes the connector, but I can do that if it is absolutely necessary
2. Also I strongly dislike leaving out the units, i.e. `mm`, as it makes the names unclearer ... what does that number mean? Did he measure in mil, in mm, in cm, in inch, in pt??? I think saving those two characters does not really shorten the name any further (you already removed outspoken Pitch and we use P instead and require the user to know what P stands for, whereas we write Pad, as we see that letter-only does not work), but confuses the meaning.

Bottomline: I can remove this (IMHO vital) info from the names, but I strongly dislike that, as it depends on an agreement/standard that is noted down somewhere [in the KLC???] and might not be known to everybody contributing! Please think about getting back at least the units into the footprint names ... especially since there are still people around that might use the imperial system and several components are on an imperial grid

Best,
JAN

**Comment by SchrodingersGat** [comment]
1. The `horizontal` and `vertical` refer to the direction of insertion of the mating connector, in relation to the plane of the board.
1. I tend to agree that the `mm` should be explicit. We have been discussing making dimensions implied as `mm` unless otherwise stated but I now am leaning more towards keeping it as a requirement. @poeschlr ?

**Comment by poeschlr** [comment]
Well it has been your suggestion to remove mm. (I had it included see https://github.com/KiCad/kicad-library/issues/1447) So if you now think we should keep it i am all for it.

For connector orientation:
connector_orientation

**Comment by SchrodingersGat** [comment]
Yes I have come around to your perspective :) I have just amended the KLC3 rules to state that dimensions must always be specified.

**Comment by jkriege2** [comment]
The two version of 45° seem non-obvious in the sketch above ... angle measured with respect to what?

**Comment by jkriege2** [comment]
I can do the other name changes this evening ... few questions remain:
1. should I use `_P` or `_Pitch` to give the pitch (in addition to my comments above a user could as a third option suspect P stands for Packagesize)? 
2. For the EdgeMounts ... should I also add Horizontal or is that then superfluous?

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

OK, I renamed ... hope it's OK like that, let me know if I should use `_Pitch`insead of `_P`. Since it was not specified, I put `_Male`/`_Female` directly behind the pin-number and optional `-HD`-specifier

**Comment by jkriege2** [comment]
I decided to go back to having `_Pitch`instead of `_P`... I find that way more understandable ... if we decide otherwise, I can still change, but the current naming is IMHO the most usefull and least mistakeable.

Best,
JAN

**Comment by jkriege2** [comment]
@SchrodingersGat So what about this PR?

**Comment by SchrodingersGat** [comment]
Thanks for the reminder:

1. NoMountingHoles

Rather than having:

* `_Vertical`
* `_Vertical_NoMountingHoles`

I would prefer to see

* `_Vertical_MountingHoles`
* `_Vertical`

e.g. the default option is not to have mounting holes. This remove the word "No" which feels a bit like a double-negative to me.

The same applies to the `_NoBox` option (specify `_Box` for those that are enclosed)

2. Explanation of terms

What exactly do the following terms mean in your scheme:

* `EdgePinOffset`
* `MountingHoleOffset`

**Comment by jkriege2** [comment]
NoBox, NoMountingHoles: OK, can do this evening
BTW: Would `_Boxed` be OK, or do you know a better wording?


EdgePinOffset and MountingHoleOffset are typical measures given in the datasheets. They describe the distance from the PCB-edge to the nearest row of pins (their centers to be exact) and from the PCB-edge to the centers of the mounting holes. Both are required, as the connectors are differentiated first by EdgePinOffset ... and then there are connectors where the mounting holes are aligned with the middle of all pin-rows, or with the first row (or possibly somewhere else ;-) ... so I chose these as they give the full description.
I used these terms as I didn't find a better name for them ... any ideas? 

Best,
JAN

**Comment by jkriege2** [comment]
PS: In the screenshot from my first post, have a look at the  angled connectors with holes:
2017-10-26 12_44_07-clipboard

**Comment by SchrodingersGat** [comment]
> BTW: Would _Boxed be OK, or do you know a better wording?

Perhaps `_Potted` (e.g. filled with epoxy?)? I'm not sure. Maybe `_Boxed` is the best term.

I understand now the `_EdgePinOffset` and `_MountingHoleOffset` thanks for the drawing. I don't know if there is a better naming scheme to use here. Do you know if there is an industry standard that applies to these types of connectors?

**Comment by jkriege2** [comment]
ABout Industry Standard: I don't think so ... what's standardized is the outline, pin-pitch/-ordering and mounting-hole of the connector itself, but the footprint is less standardized officially, although I think most manufacturers stick to the same things ... at least I tried to cover everything that I could find in this PR (therefore the large number of footprints).

**Comment by jkriege2** [comment]
Should be OK now ... I also removed some non-existents ... I think boxed without mounting holes does not exist!

**Comment by evanshultz** [comment]
@jkriege2 
First, this is a tremendous amount of work. Thanks!

I've seen the term "potted" used to mean a liquid that is applied which solidifies when cured. That doesn't seem to work for me. I think `_Housing` is better than `_Boxed` because it's more descriptive: the connector either has just pins or it has a housing around the pins.

**Comment by jkriege2** [comment]
Can do Housing ... what do you think about not annotating the housed connectors, as I think most people will think of them as "standard", but the ones with Wires Only? The maybe `_FreeWire`?

**Comment by jkriege2** [comment]
I adopted `_Housed`for the boxed connectors now .... sound better I think, thanks @evanshultz

**Comment by SchrodingersGat** [comment]
Jan thanks for the large effort here. I'm willing to merge this one, if we come up with any further improvements they can be applied later on. Awesome work :)

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
